### PR TITLE
Translate Japanese and Traditional Chinese untranslated parts.

### PR DESCRIPTION
**Pull request by satopian**
Translated the untranslated parts.

### CODE REVIEW

**Comment by bitbof** [comment]
Thanks! I noticed the translation looks a bit different from the Japanese translation of Photopea. It also has Japanese and a Gradient tool with similar settings. I think they only gave Linear-Mirror a different English name. Could you take a look?
Other than that it looks great.

**Comment by satopian** [comment]
I corrected the Japanese translation by referring to krita.
"リニア"(linear)
"バイリニア"(Bilinear)
The literal translation of "Linear-Mirror" is "線形鏡像", but Japanese people are unfamiliar with the word and do not understand the meaning.
image
↑
"バイリニア"(Bilinear)

What do you think of this translation?
Please let us know what you think.

**Comment by satopian** [comment]
> different from the Japanese translation of Photopea.

I checked the Japanese translation of photopea.com.
直線((linear)
反射( Linear-Mirror)
Is the translation more suitable for your request?
I think krita's translation and photopea.com's translation are both fine.

**Comment by bitbof** [comment]
Thanks for checking and even taking a look at Krita.
Bilinear usually refers to 2D gradients. https://commons.wikimedia.org/wiki/File:Colour_gradient_using_bilinear_interpolation.svg The Linear-Mirror gradient is 1 dimensional though.

Here's also the help page for Photoshop's gradient tool where they call it they call it 反射形: https://helpx.adobe.com/jp/photoshop/using/gradients.html

I think your original translation was probably a better fit, or we use the same wording as Photoshop. I think the translation of Krita is incorrect.

**Comment by bitbof** [comment]
> I checked the Japanese translation of photopea.com

I prefer the Photopea one to Krita. It matches Photoshop too.

**Comment by satopian** [comment]
I checked the Photoshop translation and corrected the Japanese translation again.

**Comment by bitbof** [comment]
Many thanks, and sorry for all the back and forth. I think it will make a difference if it's intuitive to understand and used in popular software. :)

**Comment by satopian** [comment]
a "線状" can be imagined as a band.
The term "直線" is confusing because it reminds me of a thin, straight line.
https://helpx.adobe.com/cn/photoshop/using/gradients.html
  'gradient-linear-mirror': {
    original: 'Linear-Mirror',
    value: '镜像线性'
  },
  'gradient-linear-mirror': {
    original: 'Linear-Mirror',
    value: '鏡像線性'
  },
I thought it would be better to use the same translation as Photoshop and photopea.com for the Chinese of this part.
Submit the pull request again.

**Pull request merged**
