### PR TITLE
Japanese translation.

### PR DESCRIPTION
**Pull request by satopian**
Translated into Japanese.
I translated some words by meaning, not by the word itself. Tilt shift is translated as "depth of field". This is because it is easier for Japanese people to understand.
Please point out if there is a problem with the translation.  

image
image

I'm sorry to add it later.
That's all.

### CODE REVIEW

**Comment by bitbof** [comment]
While I can't judge the translation itself it looks really good!

Suggestions for improvements:
- Can we replace "クリップボードにコピー" with "コピー" for key `cropcopy-btn-copy`? It is the confirmation button in the copy to clipboard & crop dialog and it's currently too big.
- Could the text for `import-psd-unsupported` be shortened? PSD can be left out if necessary. Also the image is *already* flattened, the user isn't asked to flatten it. Sorry if Google Translator and DeepL got this wrong.
- Could "Paint Tool" be translated with "ペイントツール" as seen here: https://www.systemax.jp/ja/sai/ ?
	- Admittedly this is used for Kleki's title and not Klecks. Something like this: "Kleki ペイントツール"
	- I will remove this text eventually as it's not used in Klecks.

I observed Japanese creates the following issues for Klecks (not the fault of the translation):
- Buttons with Japanese letters have a different height, and icons are misaligned
- The main tabs (*Brush | Layers | Edit | File | Settings*) in standalone are very tight.
	- I will replace Layers tab with an icon
- Small Undo Redo buttons (when window's height is smaller) don't get translated
- Somehow the X button in dialogs is smaller.

I will try fix these soon after merging.

**Comment by satopian** [comment]
Please wait for a while as we will correct the translation. It doesn't take much time.

**Comment by satopian** [comment]
>Could "Paint Tool" be translated with "ペイントツール" as seen here: https://www.systemax.jp/ja/sai/ ?
Adm

It's probably cooler to display it in English.
Not many people write "CLIP STUDIO Paint" as "クリップスタジオペイント".
So is "Painter".
For "Paint tool SAI", the title bar of the Japanese version of the app is still in English.
The product name of the Japanese version of "CLIP STUDIO PAINT" is the alphabet "CLIP STUDIO PAINT".
Japanese prefer to read relatively easy English words and write them in the alphabet.

**Comment by bitbof** [comment]
Thanks for the adjustments and your translation. This takes Klecks to a new level! Great work! 🔥

**Pull request merged**
